import {createTheme} from '@fluentui/react'
 
export const lightTheme = createTheme({
    palette: {
        themePrimary: '#922c88',
        themeLighterAlt: '#fbf4fa',
        themeLighter: '#edd3eb',
        themeLight: '#deafd9',
        themeTertiary: '#bd6eb5',
        themeSecondary: '#9f3d95',
        themeDarkAlt: '#83277a',
        themeDark: '#6e2167',
        themeDarker: '#51184c',
        neutralLighterAlt: '#faf9f8',
        neutralLighter: '#f3f2f1',
        neutralLight: '#edebe9',
        neutralQuaternaryAlt: '#e1dfdd',
        neutralQuaternary: '#d0d0d0',
        neutralTertiaryAlt: '#c8c6c4',
        neutralTertiary: '#a19f9d',
        neutralSecondary: '#605e5c',
        neutralPrimaryAlt: '#3b3a39',
        neutralPrimary: '#323130',
        neutralDark: '#201f1e',
        black: '#000000',
        white: '#ffffff',
    }});

export const darkTheme = createTheme({
    palette: {
        themePrimary: '#922c88',
        themeLighterAlt: '#fbf4fa',
        themeLighter: '#edd3eb',
        themeLight: '#deafd9',
        themeTertiary: '#bd6eb5',
        themeSecondary: '#9f3d95',
        themeDarkAlt: '#83277a',
        themeDark: '#6e2167',
        themeDarker: '#51184c',
        neutralLighterAlt: '#faf9f8',
        neutralLighter: '#f3f2f1',
        neutralLight: '#edebe9',
        neutralQuaternaryAlt: '#e1dfdd',
        neutralQuaternary: '#d0d0d0',
        neutralTertiaryAlt: '#c8c6c4',
        neutralTertiary: '#a19f9d',
        neutralSecondary: '#605e5c',
        neutralPrimaryAlt: '#3b3a39',
        neutralPrimary: '#323130',
        neutralDark: '#201f1e',
        black: '#000000',
        white: '#ffffff',
    }});